name: BlockLocator
main: stefan.blocklocator.BlockLocator
version: 0.1
author: Stefan
commands:
    bl:
        description: Finds the nearest blocks of the specified id
        permission: blocklocator.locate
        usage: /<command> [block id]
